package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import interpreter.LuaParser;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import java.util.stream.Collectors;

import static java.lang.System.lineSeparator;

public class LuaPanel {
    private JPanel rootPanel;
    private JButton getResultsButton;
    private JTextArea luaInputs;
    private JTextArea printResults;
    private JScrollPane scrollOutputs;
    private JLabel inputsLabel;
    private JLabel outputsLabel;
    private JButton fileButton;
    private JScrollPane scrollInputs;
    private final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    private final LuaParser luaParser = new LuaParser();


    //1)rendere disponibili socket di java in lua, fare funzione che permette di fare richiesta http da lua
    //2)abilitare thread java in lua, passare codice a interprete lua in un altro thread
    //  2b) ecosistema di interpreti lua che parlano tra loro
    //3)implementa in lua modulo con funzioni per creare gui in lua
    public LuaPanel() {
        PrintStream printStream = new PrintStream(outputStream);
        System.setOut(printStream);

        getResultsButton.addActionListener(e -> {
            String input = luaInputs.getText();
            luaInputs.setText("");
            String output = luaParser.parseAndRunCommands(input);
            String print = outputStream.toString();
            printResults.append(input.lines().map(line -> "> " + line + lineSeparator()).collect(Collectors.joining()));
            if (!output.equals(""))
                printResults.append(output + lineSeparator());
            else if (!print.equals(""))
                printResults.append(print);
            outputStream.reset();
        });

        fileButton.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser("src");
            fileChooser.showOpenDialog(rootPanel);
            File file = fileChooser.getSelectedFile();
            if (file != null) {
                String output = luaParser.parseAndRunFile(file.toString());
                printResults.append("> " + file + lineSeparator());
                String print = outputStream.toString();
                if (!output.equals(""))
                    printResults.append(output + lineSeparator());
                else if (!print.equals(""))
                    printResults.append(print);
                outputStream.reset();
            }
        });

        luaInputs.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {
                if (e.isShiftDown() && e.getKeyCode() == KeyEvent.VK_ENTER)
                    luaInputs.append(System.lineSeparator());
                else if (e.getKeyCode() == KeyEvent.VK_ENTER)
                    getResultsButton.doClick();
            }

        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("LuaResults");
        LuaPanel luaPanel = new LuaPanel();
        frame.setContentPane(luaPanel.rootPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                luaPanel.luaParser.closeLua();
            }
        });
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        getResultsButton = new JButton();
        getResultsButton.setText("Get Results");
        rootPanel.add(getResultsButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 50), null, null, 0, false));
        outputsLabel = new JLabel();
        outputsLabel.setText("Here are Lua's outputs");
        rootPanel.add(outputsLabel, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inputsLabel = new JLabel();
        inputsLabel.setText("Enter your inputs here:");
        rootPanel.add(inputsLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(342, 40), new Dimension(-1, 40), 0, false));
        fileButton = new JButton();
        fileButton.setText("Select from files");
        rootPanel.add(fileButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 30), null, 0, false));
        scrollOutputs = new JScrollPane();
        scrollOutputs.setVerticalScrollBarPolicy(22);
        rootPanel.add(scrollOutputs, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 200), null, null, 0, false));
        printResults = new JTextArea();
        printResults.setEditable(false);
        scrollOutputs.setViewportView(printResults);
        scrollInputs = new JScrollPane();
        rootPanel.add(scrollInputs, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 150), null, null, 0, false));
        luaInputs = new JTextArea();
        luaInputs.setText("");
        scrollInputs.setViewportView(luaInputs);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
